name: Project 3 Web App Deploy

on:
  push:
    branches: [main]
    paths: [ 'project3/frontend/**' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v5.0.0
      - name: Set up Python version
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.12'

      - name: Create and Start virtual environment and Install dependencies
        run: |
          cd project3/frontend
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v5.0.0
        with:
          name: python-app
          path: |
            project3/frontend
            !project3/frontend/antenv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v6.0.0
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        uses: Azure/webapps-deploy@v3.0.6
        id: deploy-to-webapp
        with:
          app-name: 'project3-nutritional-web'
          slot-name: 'Production'